[package]
name = "recall"
version = "1.0.1"
edition = "2024"
authors = ["Gopinath Venkatesh <gvenkatesh@example.com>"]
description = "A lightweight CLI terminal command memory and clipboard utility."
license = "MIT"
readme = "README.md"
homepage = "https://GVenkatesh-12.github.io/recall/"
repository = "https://github.com/GVenkatesh-12/recall"
keywords = ["note", "capture", "clipboard", "sqlite", "cli"]
categories = ["command-line-utilities"]

[dependencies]
clap = { version = "4.5", features = ["derive"] }
rusqlite = { version = "0.31", features = ["bundled"] }
arboard = "3.4"
dirs = "5.0"
colored = "2.1"
anyhow = "1.0"
inquire = "0.7"

[profile.release]
lto = "thin"
codegen-units = 1
strip = true

